spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db9?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: Sweety@123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect   # <-- Hibernate 6/7 correct dialect
    hibernate:
      ddl-auto: update                                      # <-- correct key (NOT dbl-auto)
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082