spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db9
    username: root
<<<<<<< HEAD
    password: Harsha@28
=======
    password:
>>>>>>> a00d10876ff491ab6fcb306786044d10ea80011d
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    # database=platform: org.hibernate.dialect.MYSQLDialect

    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      # dbl-auto: update
      ddl-auto: update

server:
  port: 8082